### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by nargxf-zz** [drabiger/estimationsChromePlugin#3]
Hi,

Suddenly from today the plugin doesn't work on OPERA, EDGE, CHROME. It is a very helpful plugin that I am counting on. I would be very helpful if somebody could fix it.

Thank you in advance

**Comment by kurapr** [comment]
Same here. I have many many teams using this feature for their Sprint Planning....I'm hoping they get it working.

**Comment by drabiger** [comment]
Sorry. I can look into this in a couple of days. Do you have any more details?

**Comment by kurapr** [comment]
Absolutely!

The Chrome Plug-In isn't summarizing the points that are captured in the subject (via [3 pts] and (2 points)) as they once did. They used to show like this:

***@***.***

Now, nothing is showing up:
***@***.***



April Kuras
Performance Innovation Consultant

Navistar, Inc
2701 Navistar Drive
Lisle, IL 60532

P: 331-332-2317
***@***.******@***.***>

**Be sure to follow us on Yammer to hear real thoughts and experiences!<https://web.yammer.com/main/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5NTk3Njg5In0/all>

**Comment by drabiger** [comment]
I updated the code to match current MS Planner changes. I submitted the changes to the Chrome extension store and got feedback that the review will take up to 30 days. Let's cross fingers it will get reviewed quicker.

**Comment by kurapr** [comment]
It works!! Nice job Dirk!! Excellent job on your response, communication and skill to figuring it out!

Kudos!  You are a Rockstar!

April Kuras
Performance Innovation Consultant

Navistar, Inc
2701 Navistar Drive
Lisle, IL 60532

P: 331-332-2317
***@***.******@***.***>

**Be sure to follow us on Yammer to hear real thoughts and experiences!<https://web.yammer.com/main/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5NTk3Njg5In0/all>
