### ISSUE TITLE
Unfortunately no longer working

### ISSUE THREAD

**Issue by kurapr** [drabiger/estimationsChromePlugin#4]
I sure hope the team of developers helps. LIke the others have mentioned, it is no longer working :(

**Comment by drabiger** [comment]
Hey kurapr, I can unfortunately only l look into this in a week from now. :/ Sorry.

**Comment by kurapr** [comment]
No problem Dirk – I really appreciate the heads up! I’ll let our teams know that it will be down for at least week 😊

Best of luck fighting the issue! Sounds like a fun challenge (yikes!?)

April Kuras
Performance Innovation Consultant

Navistar, Inc
2701 Navistar Drive
Lisle, IL 60532

P: 331-332-2317
***@***.******@***.***>

**Be sure to follow us on Yammer to hear real thoughts and experiences!<https://web.yammer.com/main/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI5NTk3Njg5In0/all>

**Comment by drabiger** [comment]
I updated the code to match current MS Planner changes. I submitted the changes to the Chrome extension store and got feedback that the review will take up to 30 days. Let's cross fingers it will get reviewed quicker.

**Comment by drabiger** [comment]
Update 1.62 is live in Chrome extension store.

**Comment by IevaPuo** [comment]
Hi, thanks it works, however it looks like it only works for first 5 buckets. We use ~ 20, could you check again the update?
