### ISSUE TITLE
Does not work for 5 or more buckets

### ISSUE THREAD

**Issue by drabiger** [drabiger/estimationsChromePlugin#5]
Hi, thanks it works, however it looks like it only works for first 5 buckets. We use ~ 20, could you check again the update?

_Originally posted by @IevaPuo in https://github.com/drabiger/estimationsChromePlugin/issues/4#issuecomment-1030839663_

**Comment by drabiger** [comment]
True, I can confirm that. Will look into it.

**Comment by drabiger** [comment]
OK. Fixed. Issue was that MS Planner only inserts DOM of columns (buckets) once they are in the browser's viewport. Fix is submitted to Chrome Extension store as version 1.63.

**Comment by IevaPuo** [comment]
Works :) Thanks!!!
