### ISSUE TITLE
hi, this plugin stopped counting (numbers) from yesterday. Please fix. 

### ISSUE THREAD

**Issue by IevaPuo** [drabiger/estimationsChromePlugin#6]

**Comment by drabiger** [comment]
MS Planner changed a class name. I modified the extension's css selector to match this change. There will be a new version 1.64 of the extension that is currently under review by Google.

**Comment by drabiger** [comment]
Will be fixed with version 1.65 of the plugin. Fasted way to get the version is to uninstall the extension, then install it again.
