### ISSUE TITLE
Microsoft Planner URL Change Causing Plugin to Stop Working

### ISSUE THREAD

**Issue by anishaga** [drabiger/estimationsChromePlugin#9]
Description:

Our plugin is no longer functioning as expected because Microsoft has changed the URL structure of Planner. The previous URL pattern (https://tasks.office.com/*/Planner*) is no longer valid, and Microsoft now uses a different domain (https://planner.cloud.microsoft/*).

As a result, the plugin is not able to inject the necessary scripts and styles into the new Planner URL, causing the functionality to break.

**Comment by drabiger** [comment]
@anishaga Thank you for submiting the PR. I've just uploaded the new version 1.66 with your change to the Chrome store. It's currently in review by Google.

I'm not using the plugin myself, any more. Could you double check if it's working and update the ticket?

**Comment by anishaga** [comment]
@drabiger the plugin update is now live on Chrome Web Store and it is working fine with the latest update.
